export interface Question {
  id: number;
  /** Optional topic; with two or more topics every round starts with the category carousel. */
  category?: string;
  question: string;
  answers: [string, string, string, string];
  /** Index 0..3 of the correct answer. */
  correctAnswer: 0 | 1 | 2 | 3;
}

/** Default question bank; the live list is stored in data/questions.json and edited on the /questions page. */
export const QUESTIONS: Question[] = [
  {
    id: 1,
    category: 'География',
    question: 'Какая страна самая большая по площади?',
    answers: ['Канада', 'Китай', 'США', 'Россия'],
    correctAnswer: 3,
  },
  {
    id: 2,
    category: 'География',
    question: 'Какой океан самый большой?',
    answers: ['Атлантический', 'Индийский', 'Тихий', 'Северный Ледовитый'],
    correctAnswer: 2,
  },
  {
    id: 3,
    category: 'География',
    question: 'Какой город является столицей Австралии?',
    answers: ['Сидней', 'Мельбурн', 'Канберра', 'Перт'],
    correctAnswer: 2,
  },
  {
    id: 4,
    category: 'География',
    question: 'На каком материке находится Египет?',
    answers: ['Азия', 'Африка', 'Европа', 'Южная Америка'],
    correctAnswer: 1,
  },
  {
    id: 5,
    category: 'География',
    question: 'Какая река самая длинная в Европе?',
    answers: ['Дунай', 'Волга', 'Рейн', 'Днепр'],
    correctAnswer: 1,
  },
  {
    id: 6,
    category: 'География',
    question: 'Какая гора самая высокая в мире?',
    answers: ['Эверест', 'К2', 'Монблан', 'Эльбрус'],
    correctAnswer: 0,
  },
  {
    id: 7,
    category: 'География',
    question: 'Какое озеро самое глубокое в мире?',
    answers: ['Байкал', 'Ладожское', 'Виктория', 'Онтарио'],
    correctAnswer: 0,
  },
  {
    id: 8,
    category: 'Наука',
    question: 'Сколько планет в Солнечной системе?',
    answers: ['7', '8', '9', '10'],
    correctAnswer: 1,
  },
  {
    id: 9,
    category: 'Наука',
    question: 'Какой газ растения поглощают при фотосинтезе?',
    answers: ['Кислород', 'Азот', 'Углекислый газ', 'Водород'],
    correctAnswer: 2,
  },
  {
    id: 10,
    category: 'Наука',
    question: 'Какая планета известна как «Красная планета»?',
    answers: ['Венера', 'Юпитер', 'Сатурн', 'Марс'],
    correctAnswer: 3,
  },
  {
    id: 11,
    category: 'Наука',
    question: 'Какой химический символ у золота?',
    answers: ['Ag', 'Au', 'Fe', 'Cu'],
    correctAnswer: 1,
  },
  {
    id: 12,
    category: 'Наука',
    question: 'Сколько костей у взрослого человека?',
    answers: ['106', '206', '306', '406'],
    correctAnswer: 1,
  },
  {
    id: 13,
    category: 'Наука',
    question: 'Какая планета ближе всего к Солнцу?',
    answers: ['Венера', 'Земля', 'Меркурий', 'Марс'],
    correctAnswer: 2,
  },
  {
    id: 14,
    category: 'Наука',
    question: 'Какой химический элемент обозначается символом O?',
    answers: ['Золото', 'Олово', 'Осмий', 'Кислород'],
    correctAnswer: 3,
  },
  {
    id: 15,
    category: 'Литература',
    question: 'Кто написал роман «Война и мир»?',
    answers: ['Ф. Достоевский', 'А. Чехов', 'А. Пушкин', 'Л. Толстой'],
    correctAnswer: 3,
  },
  {
    id: 16,
    category: 'Литература',
    question: 'Кто автор романа в стихах «Евгений Онегин»?',
    answers: ['М. Лермонтов', 'А. Пушкин', 'Н. Гоголь', 'И. Тургенев'],
    correctAnswer: 1,
  },
  {
    id: 17,
    category: 'Литература',
    question: 'Кто автор романа «Преступление и наказание»?',
    answers: ['Ф. Достоевский', 'Л. Толстой', 'А. Чехов', 'И. Бунин'],
    correctAnswer: 0,
  },
  {
    id: 18,
    category: 'Литература',
    question: 'Кто написал роман «Мастер и Маргарита»?',
    answers: ['Н. Гоголь', 'М. Булгаков', 'А. Чехов', 'И. Тургенев'],
    correctAnswer: 1,
  },
  {
    id: 19,
    category: 'Литература',
    question: 'Кто написал «Приключения Тома Сойера»?',
    answers: ['Ч. Диккенс', 'Э. Хемингуэй', 'Дж. Лондон', 'М. Твен'],
    correctAnswer: 3,
  },
  {
    id: 20,
    category: 'Литература',
    question: 'Кто автор стихотворения «Мойдодыр»?',
    answers: ['С. Маршак', 'К. Чуковский', 'А. Барто', 'С. Михалков'],
    correctAnswer: 1,
  },
  {
    id: 21,
    category: 'Литература',
    question: 'Кто автор книг о Гарри Поттере?',
    answers: ['Дж. Толкин', 'Дж. Роулинг', 'Л. Кэрролл', 'К. Льюис'],
    correctAnswer: 1,
  },
  {
    id: 22,
    category: 'История',
    question: 'Кто первым в мире полетел в космос?',
    answers: ['Ю. Гагарин', 'Г. Титов', 'Н. Армстронг', 'В. Терешкова'],
    correctAnswer: 0,
  },
  {
    id: 23,
    category: 'История',
    question: 'В каком году началась Вторая мировая война?',
    answers: ['1941', '1914', '1945', '1939'],
    correctAnswer: 3,
  },
  {
    id: 24,
    category: 'История',
    question: 'Какая цивилизация построила пирамиды в Гизе?',
    answers: ['Римляне', 'Древние египтяне', 'Майя', 'Греки'],
    correctAnswer: 1,
  },
  {
    id: 25,
    category: 'История',
    question: 'Кто был первым президентом США?',
    answers: ['А. Линкольн', 'Т. Джефферсон', 'Дж. Вашингтон', 'Б. Франклин'],
    correctAnswer: 2,
  },
  {
    id: 26,
    category: 'История',
    question: 'В каком году человек впервые высадился на Луне?',
    answers: ['1969', '1961', '1972', '1965'],
    correctAnswer: 0,
  },
  {
    id: 27,
    category: 'История',
    question: 'В каком году распался СССР?',
    answers: ['1985', '1989', '1991', '1993'],
    correctAnswer: 2,
  },
  {
    id: 28,
    category: 'История',
    question: 'Кто основал Санкт-Петербург?',
    answers: ['Иван Грозный', 'Пётр I', 'Екатерина II', 'Александр I'],
    correctAnswer: 1,
  },
  {
    id: 29,
    category: 'Спорт',
    question: 'Сколько игроков одной команды одновременно на поле в футболе?',
    answers: ['9', '10', '11', '12'],
    correctAnswer: 2,
  },
  {
    id: 30,
    category: 'Спорт',
    question: 'В каком виде спорта играют шайбой?',
    answers: ['Хоккей', 'Гольф', 'Теннис', 'Бейсбол'],
    correctAnswer: 0,
  },
  {
    id: 31,
    category: 'Спорт',
    question: 'В каком городе прошли зимние Олимпийские игры 2014 года?',
    answers: ['Лондон', 'Сочи', 'Рио-де-Жанейро', 'Пекин'],
    correctAnswer: 1,
  },
  {
    id: 32,
    category: 'Спорт',
    question: 'Сколько колец на олимпийском флаге?',
    answers: ['3', '4', '5', '6'],
    correctAnswer: 2,
  },
  {
    id: 33,
    category: 'Спорт',
    question: 'В каком виде спорта используют ракетку и волан?',
    answers: ['Бадминтон', 'Сквош', 'Теннис', 'Настольный теннис'],
    correctAnswer: 0,
  },
  {
    id: 34,
    category: 'Спорт',
    question: 'Сколько минут длится футбольный матч без добавленного времени?',
    answers: ['60', '80', '90', '120'],
    correctAnswer: 2,
  },
  {
    id: 35,
    category: 'Спорт',
    question: 'Сборная какой страны выиграла чемпионат мира по футболу 2018 года?',
    answers: ['Хорватия', 'Франция', 'Бразилия', 'Германия'],
    correctAnswer: 1,
  },
  {
    id: 36,
    category: 'Музыка',
    question: 'Сколько клавиш у стандартного фортепиано?',
    answers: ['66', '76', '88', '100'],
    correctAnswer: 2,
  },
  {
    id: 37,
    category: 'Музыка',
    question: 'Какая группа исполнила песню «Bohemian Rhapsody»?',
    answers: ['The Beatles', 'ABBA', 'Pink Floyd', 'Queen'],
    correctAnswer: 3,
  },
  {
    id: 38,
    category: 'Музыка',
    question: 'Какой инструмент называют «королём инструментов»?',
    answers: ['Орган', 'Гитара', 'Скрипка', 'Флейта'],
    correctAnswer: 0,
  },
  {
    id: 39,
    category: 'Музыка',
    question: 'Сколько струн у классической гитары?',
    answers: ['4', '5', '6', '7'],
    correctAnswer: 2,
  },
  {
    id: 40,
    category: 'Музыка',
    question: 'Кто написал балет «Лебединое озеро»?',
    answers: ['С. Рахманинов', 'П. Чайковский', 'Н. Римский-Корсаков', 'М. Глинка'],
    correctAnswer: 1,
  },
  {
    id: 41,
    category: 'Музыка',
    question: 'Какая певица исполнила песню «Rolling in the Deep»?',
    answers: ['Бейонсе', 'Рианна', 'Адель', 'Тейлор Свифт'],
    correctAnswer: 2,
  },
  {
    id: 42,
    category: 'Музыка',
    question: 'Какая группа выпустила альбом «Abbey Road»?',
    answers: ['Led Zeppelin', 'Rolling Stones', 'Queen', 'The Beatles'],
    correctAnswer: 3,
  },
  {
    id: 43,
    category: 'Кино и сериалы',
    question: 'Кто режиссёр фильма «Титаник» (1997)?',
    answers: ['С. Спилберг', 'Дж. Кэмерон', 'К. Нолан', 'Р. Скотт'],
    correctAnswer: 1,
  },
  {
    id: 44,
    category: 'Кино и сериалы',
    question: 'Какой актёр сыграл капитана Джека Воробья в «Пиратах Карибского моря»?',
    answers: ['Джонни Депп', 'Брэд Питт', 'Орландо Блум', 'Том Харди'],
    correctAnswer: 0,
  },
  {
    id: 45,
    category: 'Кино и сериалы',
    question: 'Как называется континент, где находится Королевская Гавань в «Игре престолов»?',
    answers: ['Нарния', 'Мордор', 'Эссос', 'Вестерос'],
    correctAnswer: 3,
  },
  {
    id: 46,
    category: 'Кино и сериалы',
    question: 'В каком сериале главного героя зовут Уолтер Уайт?',
    answers: ['Доктор Хаус', 'Во все тяжкие', 'Клиника', 'Менталист'],
    correctAnswer: 1,
  },
  {
    id: 47,
    category: 'Кино и сериалы',
    question: 'В каком сериале шесть друзей — Рэйчел, Моника, Фиби, Джоуи, Чендлер и Росс?',
    answers: ['Как я встретил вашу маму', 'Теория большого взрыва', 'Клиника', 'Друзья'],
    correctAnswer: 3,
  },
  {
    id: 48,
    category: 'Кино и сериалы',
    question: 'Как зовут главного героя фильма «Матрица»?',
    answers: ['Морфеус', 'Тринити', 'Нео', 'Смит'],
    correctAnswer: 2,
  },
  {
    id: 49,
    category: 'Кино и сериалы',
    question: 'В каком мультфильме рыбка-клоун ищет потерявшегося сына?',
    answers: ['Тачки', 'В поисках Немо', 'Шрек', 'Гадкий я'],
    correctAnswer: 1,
  },
  {
    id: 50,
    category: 'Видеоигры',
    question: 'Как зовут итальянского водопроводчика — главного героя игр от Nintendo?',
    answers: ['Луиджи', 'Марио', 'Варио', 'Йоши'],
    correctAnswer: 1,
  },
  {
    id: 51,
    category: 'Видеоигры',
    question: 'В какой игре нужно добывать блоки и строить из них собственный мир?',
    answers: ['Fortnite', 'Roblox', 'Terraria', 'Minecraft'],
    correctAnswer: 3,
  },
  {
    id: 52,
    category: 'Видеоигры',
    question: 'Как зовут жёлтого покемона — символа франшизы Pokémon?',
    answers: ['Чармандер', 'Бульбазавр', 'Пикачу', 'Сквиртл'],
    correctAnswer: 2,
  },
  {
    id: 53,
    category: 'Видеоигры',
    question: 'Какая компания создала игру Fortnite?',
    answers: ['Valve', 'Epic Games', 'Blizzard', 'Ubisoft'],
    correctAnswer: 1,
  },
  {
    id: 54,
    category: 'Видеоигры',
    question: 'К какому жанру относятся Dota 2 и League of Legends?',
    answers: ['Шутер', 'Платформер', 'MOBA', 'Гонки'],
    correctAnswer: 2,
  },
  {
    id: 55,
    category: 'Видеоигры',
    question: 'Как зовут героиню серии игр Tomb Raider?',
    answers: ['Элли', 'Зельда', 'Лара Крофт', 'Кортана'],
    correctAnswer: 2,
  },
  {
    id: 56,
    category: 'Видеоигры',
    question: 'В какой стране была создана серия игр «Ведьмак»?',
    answers: ['Россия', 'Чехия', 'Швеция', 'Польша'],
    correctAnswer: 3,
  },
];
